apiVersion: backstage.io/v1alpha1
kind: Environment
metadata:
  name: "Enviroment1"
  environment:
    k8s_version: 1.28
    cidr_block: 10.50.0.0/16
    instance_type: typeX
    capacity_type: 111
    node_quantity: 8
    max_node_quantity: 3
    domain: test.com
    hosted_zone_id: sfdfsjfs
    rolearn: testerole 
    vpc: xpto-vpc
    nginx: xpto-nginx
    cert_manager_issuer_type: staging
    cert_manager_email: valber@teste.com
    public_subnets:
    - "10.50.1.0/24"
    - "10.50.2.0/24"
    - "10.50.3.0/24"
    private_subnets: 
    - "10.50.4.0/24"
    - "10.50.5.0/24"
    - "10.50.6.0/24" 
  annotations:
    github.com/project-slug: ValberJunior/Enviroment1
    backstage.io/techdocs-ref: dir:.
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
