apiVersion: backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "teste-kubernetes"
  environment:
    domain: test.com
    hostedZoneId: sfdfsjfs
    vpc: xpto-vpc
    certManagerIssuerType: staging
    certManagerEmail: valber@teste.com
  annotations:
    github.com/project-slug: ValberJunior/ClusterA
    backstage.io/techdocs-ref: dir:.
    veecode/cluster-name: "teste-kubernetes"
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/infra"
  dependsOn: ["environment:default/Enviroment_Ecs"]
