apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-teste
  title: ap-teste
  publishedAt: "2023-10-04 19:33:10"
  description: 'ap-teste Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.'
  tags:
    - teste
spec:
  type: openapi
  lifecycle: prod
  owner: consumer
  definition: |-
    openapi: 3.0.0
    info:
        description: 'ap-teste Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.'
        version: 1.0.2
        title: ap-teste
        termsOfService: http://swagger.io/terms/
        contact:
            email: apiteam@swagger.io
        license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html
    servers:
        - url: https://rest.apr.vee.codes/ap-teste
    tags:
        - name: spec
          description: Health
          externalDocs:
            description: Find out more
            url: http://swagger.io
    paths: {}
    components: {}
